-- SQL Migration for App Versions (Versões do Aplicativo)

CREATE TABLE IF NOT EXISTS app_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_number TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  update_type TEXT NOT NULL, -- 'Nova funcionalidade', 'Melhoria', 'Correção de erro', 'Ajuste visual', 'Segurança', 'Desempenho'
  status TEXT NOT NULL, -- 'Desenvolvimento', 'Testes', 'Publicada'
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE app_versions ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access to authenticated users" 
ON app_versions FOR SELECT 
TO authenticated 
USING (true);

-- Allow write/update/delete access to authenticated users
CREATE POLICY "Allow write access to authenticated users" 
ON app_versions FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
