-- Tabela de Períodos
CREATE TABLE IF NOT EXISTS periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  start_date DATE,
  end_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Matérias (Subjects)
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_year TEXT,
  subject_name TEXT NOT NULL,
  professor TEXT,
  workload NUMERIC,
  period_id BIGINT REFERENCES periods(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Presenças
CREATE TABLE IF NOT EXISTS presencas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_materia_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  periodo_id BIGINT REFERENCES periods(id) ON DELETE CASCADE,
  aula_1 BOOLEAN DEFAULT FALSE,
  aula_2 BOOLEAN DEFAULT FALSE,
  aula_3 BOOLEAN DEFAULT FALSE,
  aula_4 BOOLEAN DEFAULT FALSE,
  data_aula_1 DATE,
  data_aula_2 DATE,
  data_aula_3 DATE,
  data_aula_4 DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Notas e Atividades
CREATE TABLE IF NOT EXISTS notas_atividades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_materia_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  periodo_id BIGINT REFERENCES periods(id) ON DELETE CASCADE,
  atividade_1_nota NUMERIC DEFAULT 0,
  atividade_2_nota NUMERIC DEFAULT 0,
  prova_nota NUMERIC DEFAULT 0,
  atividade_1_status TEXT DEFAULT 'Não iniciada',
  atividade_2_status TEXT DEFAULT 'Não iniciada',
  atividade_1_prazo DATE,
  atividade_2_prazo DATE,
  prova_data DATE,
  atividade_1_inicio DATE,
  atividade_2_inicio DATE,
  prova_inicio DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Conteúdos Web
CREATE TABLE IF NOT EXISTS conteudos_web (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_materia_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  periodo_id BIGINT REFERENCES periods(id) ON DELETE CASCADE,
  conteudo_1_assistido BOOLEAN DEFAULT FALSE,
  conteudo_2_assistido BOOLEAN DEFAULT FALSE,
  conteudo_3_assistido BOOLEAN DEFAULT FALSE,
  conteudo_4_assistido BOOLEAN DEFAULT FALSE,
  data_1 DATE,
  data_2 DATE,
  data_3 DATE,
  data_4 DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comandos de Alteração (para garantir que colunas novas existam em tabelas já criadas)
-- Adicionar colunas de data de início para atividades e provas
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_1_inicio DATE;
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_2_inicio DATE;
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS prova_inicio DATE;

-- Garantir que as colunas de prazo final existam
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_1_prazo DATE;
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_2_prazo DATE;
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS prova_data DATE;

-- Garantir que as colunas de notas existam
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_1_nota NUMERIC DEFAULT 0;
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_2_nota NUMERIC DEFAULT 0;
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS prova_nota NUMERIC DEFAULT 0;

-- Garantir que as colunas de status existam
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_1_status TEXT DEFAULT 'Não iniciada';
ALTER TABLE notas_atividades ADD COLUMN IF NOT EXISTS atividade_2_status TEXT DEFAULT 'Não iniciada';
