-- Create Fixed Accounts Table
CREATE TABLE IF NOT EXISTS fixed_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  category TEXT NOT NULL,
  sub_category TEXT,
  amount NUMERIC(10, 2) NOT NULL,
  due_date DATE NOT NULL,
  month_reference TEXT NOT NULL,
  status TEXT DEFAULT 'pendente',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE fixed_accounts ENABLE ROW LEVEL SECURITY;

-- Security Policies
CREATE POLICY "Users can manage their own fixed accounts" ON fixed_accounts FOR ALL USING (auth.uid() = user_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_fixed_accounts_user_id ON fixed_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_fixed_accounts_month_reference ON fixed_accounts(month_reference);
